### PR TITLE
Move to MAX Framework (v1.1.0)

### PR DESCRIPTION
**Pull request by MLnick**

### CODE REVIEW

**Comment by bdwyer2** [comment]
Maybe increasing `sleep` to `30` on line 9 of `.travis.yml` will fix the tests

**Comment by MLnick** [comment]
@bdwyer2 I forgot to change the `app.py` file! Working now

**Comment by djalova** [comment]
This might be a minor nit, but should we start cleaning up our imports according to pep8 convention?

**Comment by MLnick** [comment]
@djalova probably yes. Why does `flake8` not pick that up by the way on Travis?

**Comment by MLnick** [comment]
@djalova I merged this for now, we can follow up import cleanups in a separate task as that will need to be coordinated across models.

**Pull request merged**
